phenotypes:
    Apolipoprotein_A:
        correction_method: Bonferroni 
    Apolipoprotein_B:
        correction_method: Bonferroni 
    Calcium:
        correction_method: Bonferroni 
    Cholesterol_statin_corrected:
        correction_method: Bonferroni 
    HDL_cholesterol:
        correction_method: Bonferroni 
    IGF_1:
        correction_method: Bonferroni 
    LDL_direct_statin_corrected:
        correction_method: Bonferroni 
    Lymphocyte_percentage:
        correction_method: Bonferroni 
    Mean_corpuscular_volume:
        correction_method: Bonferroni 
    Mean_platelet_thrombocyte_volume:
        correction_method: Bonferroni 
    Mean_reticulocyte_volume:
        correction_method: Bonferroni 
    Neutrophill_count:
        correction_method: Bonferroni 
    Platelet_count:
        correction_method: Bonferroni 
    Platelet_crit:
        correction_method: Bonferroni 
    Platelet_distribution_width:
        correction_method: Bonferroni 
    Red_blood_cell_erythrocyte_count:
        correction_method: Bonferroni 
    SHBG:
        correction_method: Bonferroni 
    Standing_height:
        correction_method: Bonferroni 
    Total_bilirubin:
        correction_method: Bonferroni 
    Triglycerides:
        correction_method: Bonferroni 
    Urate:
        correction_method: Bonferroni 

baseline_results:
    -
        base: baseline_results
        type: plof/burden
    -
        base: baseline_results
        type: missense/burden
    -
        base: baseline_results
        type: plof/skat
    -
        base: baseline_results
        type: missense/skat

cv_path: sample_files
n_folds: 5
alpha: 0.05

model_dir: ./pretrained_models
n_burden_chunks: 5
n_regression_chunks: 2

n_repeats: 6
do_scoretest: True


data:
    gt_file: genotypes.h5
    variant_file: variants.parquet
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_file: phenotypes.parquet
        y_transformation: quantile_transform
        x_phenotypes:
            - age
            - age2
            - age_sex
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: annotations.parquet
        annotations:
            - Consequence_synonymous_variant
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_raw
            - sift_score
            - polyphen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - condel_score
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI_score
            - AbSplice_DNA
            - DeepRipe_plus_QKI_lip_hg2
            - DeepRipe_plus_QKI_clip_k5
            - DeepRipe_plus_KHDRBS1_clip_k5
            - DeepRipe_plus_ELAVL1_parclip
            - DeepRipe_plus_TARDBP_parclip
            - DeepRipe_plus_HNRNPD_parclip
            - DeepRipe_plus_MBNL1_parclip
            - DeepRipe_plus_QKI_parclip
            - SpliceAI_delta_score
            - alphamissense
        gene_file: protein_coding_genes.parquet
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - combined_UKB_NFE_AF_MB
                    - CADD_raw
                    - sift_score
                    - polyphen_score
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_inframe_insertion
                    - Consequence_inframe_deletion
                    - Consequence_missense_variant
                    - Consequence_protein_altering_variant
                    - Consequence_splice_region_variant
                    - condel_score
                    - DeepSEA_PC_1
                    - DeepSEA_PC_2
                    - DeepSEA_PC_3
                    - DeepSEA_PC_4
                    - DeepSEA_PC_5
                    - DeepSEA_PC_6
                    - PrimateAI_score
                    - AbSplice_DNA
                    - DeepRipe_plus_QKI_lip_hg2
                    - DeepRipe_plus_QKI_clip_k5
                    - DeepRipe_plus_KHDRBS1_clip_k5
                    - DeepRipe_plus_ELAVL1_parclip
                    - DeepRipe_plus_TARDBP_parclip
                    - DeepRipe_plus_HNRNPD_parclip
                    - DeepRipe_plus_MBNL1_parclip
                    - DeepRipe_plus_QKI_parclip
                    - SpliceAI_delta_score
                    - alphamissense
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-3"
                    Consequence_synonymous_variant:  "Consequence_synonymous_variant == 1" #this ensures that only missense variants are used for association testing
                gene_file: protein_coding_genes.parquet
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 16
        num_workers: 10
