phenotypes <- c(
  'Apolipoprotein_A',
  'Apolipoprotein_B',
  'Calcium',
  'Cholesterol',
  'HDL_cholesterol',
  'IGF_1',
  'LDL_direct',
  'SHBG',
  'Total_bilirubin',
  'Triglycerides',
  'Urate',
  'Mean_corpuscular_volume',
  'Platelet_count',
  'Mean_platelet_thrombocyte_volume',
  'Platelet_crit',
  'Standing_height',
  'Mean_reticulocyte_volume',
  'Platelet_distribution_width',
  'Lymphocyte_percentage',
  'Neutrophill_count',
  'Red_blood_cell_erythrocyte_count',
  "Body_mass_index_BMI",
  "Glucose",
  "Vitamin_D",
  "Albumin",
  "Total_protein",
  "Cystatin_C",
  "Gamma_glutamyltransferase",
  "Alkaline_phosphatase",
  "Creatinine",
  "Whole_body_fat_free_mass",
  "Forced_expiratory_volume_in_1_second_FEV1",
  "QTC_interval",
  "Glycated_haemoglobin_HbA1c",
  "WHR",
  "WHR_Body_mass_index_BMI_corrected"
)

phenotypes_deeprvat <- c(
  'Apolipoprotein A',
  'Apolipoprotein B',
  'Calcium',
  'Cholesterol',
  'HDL cholesterol',
  'IGF-1',
  'LDL direct',
  'SHBG',
  'Total bilirubin',
  'Triglycerides',
  'Urate',
  'Mean corpuscular volume',
  'Platelet count',
  'MPTVS',
  'Platelet crit',
  'Standing height',
  'Mean reticulocyte volume',
  'Platelet distribution width',
  'Lymphocyte percentage',
  'Neutrophill count',
  'Erythrocyte count',
  "Body mass index BMI",
  "Glucose",
  "Vitamin D",
  "Albumin",
  "Total protein",
  "Cystatin C",
  "Gamma glutamyltransferase",
  "Alkaline phosphatase",
  "Creatinine",
  "Whole body fat free mass",
  "Forced expiratory volume in 1 second FEV1",
  "QTC interval",
  "Glycated haemoglobin HbA1c",
  "WHR",
  "WHR Body mass index BMI corrected"
)

names(phenotypes_deeprvat) = phenotypes