alpha: 0.05
baseline_results:
- base: baseline_results
  type: plof/burden
- base: baseline_results
  type: missense/burden
- base: baseline_results
  type: plof/skat
- base: baseline_results
  type: missense/skat
data:
  dataloader_config:
    batch_size: 16
    num_workers: 10
  dataset_config:
    annotation_file: annotations.parquet
    annotations:
    - combined_UKB_NFE_AF
    - combined_UKB_NFE_AF_MB
    - CADD_PHRED
    - CADD_raw
    - sift_score
    - polyphen_score
    - Consequence_splice_acceptor_variant
    - Consequence_splice_donor_variant
    - Consequence_stop_gained
    - Consequence_frameshift_variant
    - Consequence_stop_lost
    - Consequence_start_lost
    - Consequence_inframe_insertion
    - Consequence_inframe_deletion
    - Consequence_missense_variant
    - Consequence_protein_altering_variant
    - Consequence_splice_region_variant
    - condel_score
    - DeepSEA_PC_1
    - DeepSEA_PC_2
    - DeepSEA_PC_3
    - DeepSEA_PC_4
    - DeepSEA_PC_5
    - DeepSEA_PC_6
    - PrimateAI_score
    - AbSplice_DNA
    - DeepRipe_plus_QKI_lip_hg2
    - DeepRipe_plus_QKI_clip_k5
    - DeepRipe_plus_KHDRBS1_clip_k5
    - DeepRipe_plus_ELAVL1_parclip
    - DeepRipe_plus_TARDBP_parclip
    - DeepRipe_plus_HNRNPD_parclip
    - DeepRipe_plus_MBNL1_parclip
    - DeepRipe_plus_QKI_parclip
    - SpliceAI_delta_score
    - alphamissense
    gene_file: protein_coding_genes.parquet
    min_common_af:
      combined_UKB_NFE_AF: 0.01
    phenotype_file: phenotypes.parquet
    rare_embedding:
      config:
        annotations:
        - combined_UKB_NFE_AF_MB
        - CADD_raw
        - sift_score
        - polyphen_score
        - Consequence_splice_acceptor_variant
        - Consequence_splice_donor_variant
        - Consequence_stop_gained
        - Consequence_frameshift_variant
        - Consequence_stop_lost
        - Consequence_start_lost
        - Consequence_inframe_insertion
        - Consequence_inframe_deletion
        - Consequence_missense_variant
        - Consequence_protein_altering_variant
        - Consequence_splice_region_variant
        - condel_score
        - DeepSEA_PC_1
        - DeepSEA_PC_2
        - DeepSEA_PC_3
        - DeepSEA_PC_4
        - DeepSEA_PC_5
        - DeepSEA_PC_6
        - PrimateAI_score
        - AbSplice_DNA
        - DeepRipe_plus_QKI_lip_hg2
        - DeepRipe_plus_QKI_clip_k5
        - DeepRipe_plus_KHDRBS1_clip_k5
        - DeepRipe_plus_ELAVL1_parclip
        - DeepRipe_plus_TARDBP_parclip
        - DeepRipe_plus_HNRNPD_parclip
        - DeepRipe_plus_MBNL1_parclip
        - DeepRipe_plus_QKI_parclip
        - SpliceAI_delta_score
        - alphamissense
        gene_file: protein_coding_genes.parquet
        low_memory: true
        thresholds:
          CADD_PHRED: CADD_PHRED > 5
          combined_UKB_NFE_AF: combined_UKB_NFE_AF < 1e-3
        verbose: true
      type: PaddedAnnotations
    sample_file: samples.pkl
    use_common_variants: false
    use_rare_variants: true
    verbose: true
    x_phenotypes:
    - age
    - age2
    - age_sex
    - genetic_sex
    - genetic_PC_1
    - genetic_PC_2
    - genetic_PC_3
    - genetic_PC_4
    - genetic_PC_5
    - genetic_PC_6
    - genetic_PC_7
    - genetic_PC_8
    - genetic_PC_9
    - genetic_PC_10
    - genetic_PC_11
    - genetic_PC_12
    - genetic_PC_13
    - genetic_PC_14
    - genetic_PC_15
    - genetic_PC_16
    - genetic_PC_17
    - genetic_PC_18
    - genetic_PC_19
    - genetic_PC_20
    y_transformation: quantile_transform
  gt_file: genotypes.h5
  variant_file: variants.parquet
do_scoretest: true
early_stopping:
  min_delta: 1.0e-05
  mode: min
  patience: 3
  verbose: true
hyperparameter_optimization:
  direction: maximize
  n_trials: 1
  sampler:
    config: {}
    type: TPESampler
model:
  checkpoint: combined_agg.pt
  config:
    activation: LeakyReLU
    metrics:
      all:
        MAE: {}
        MSE: {}
        PearsonCorrTorch: {}
        RSquared: {}
      loss: MSE
      objective: MSE
      objective_mode: min
    optimizer:
      config: {}
      type: AdamW
    phi_hidden_dim: 20
    phi_layers: 2
    pool: max
    rho_hidden_dim: 10
    rho_layers: 3
    use_sigmoid: true
  model_collection: agg_models
  type: DeepSet
n_burden_chunks: 4
n_regression_chunks: 2
n_repeats: 6
phenotypes:
  Albumin:
    baseline_phenotype: Albumin
    correction_method: Bonferroni
  Alkaline_phosphatase:
    baseline_phenotype: Alkaline_phosphatase
    correction_method: Bonferroni
  Apolipoprotein_A:
    baseline_phenotype: Apolipoprotein_A
    correction_method: Bonferroni
    n_training_genes: 40
  Apolipoprotein_B:
    baseline_phenotype: Apolipoprotein_B
    correction_method: Bonferroni
    n_training_genes: 40
  Body_mass_index_BMI:
    baseline_phenotype: Body_mass_index_BMI
    correction_method: Bonferroni
  Calcium:
    baseline_phenotype: Calcium
    correction_method: Bonferroni
    n_training_genes: 40
  Cholesterol_statin_corrected:
    baseline_phenotype: Cholesterol_statin_corrected
    correction_method: Bonferroni
    n_training_genes: 40
  Creatinine:
    baseline_phenotype: Creatinine
    correction_method: Bonferroni
  Cystatin_C:
    baseline_phenotype: Cystatin_C
    correction_method: Bonferroni
  Forced_expiratory_volume_in_1_second_FEV1:
    baseline_phenotype: Forced_expiratory_volume_in_1_second_FEV1
    correction_method: Bonferroni
  Gamma_glutamyltransferase:
    baseline_phenotype: Gamma_glutamyltransferase
    correction_method: Bonferroni
  Glucose:
    baseline_phenotype: Glucose
    correction_method: Bonferroni
  Glycated_haemoglobin_HbA1c:
    baseline_phenotype: Glycated_haemoglobin_HbA1c
    correction_method: Bonferroni
  HDL_cholesterol:
    baseline_phenotype: HDL_cholesterol
    correction_method: Bonferroni
    n_training_genes: 40
  IGF_1:
    baseline_phenotype: IGF_1
    correction_method: Bonferroni
    n_training_genes: 40
  LDL_direct_statin_corrected:
    baseline_phenotype: LDL_direct_statin_corrected
    correction_method: Bonferroni
    n_training_genes: 40
  Lymphocyte_percentage:
    baseline_phenotype: Lymphocyte_percentage
    correction_method: Bonferroni
    n_training_genes: 40
  Mean_corpuscular_volume:
    baseline_phenotype: Mean_corpuscular_volume
    correction_method: Bonferroni
    n_training_genes: 40
  Mean_platelet_thrombocyte_volume:
    baseline_phenotype: Mean_platelet_thrombocyte_volume
    correction_method: Bonferroni
    n_training_genes: 40
  Mean_reticulocyte_volume:
    baseline_phenotype: Mean_reticulocyte_volume
    correction_method: Bonferroni
    n_training_genes: 40
  Neutrophill_count:
    baseline_phenotype: Neutrophill_count
    correction_method: Bonferroni
    n_training_genes: 40
  Platelet_count:
    baseline_phenotype: Platelet_count
    correction_method: Bonferroni
    n_training_genes: 40
  Platelet_crit:
    baseline_phenotype: Platelet_crit
    correction_method: Bonferroni
    n_training_genes: 40
  Platelet_distribution_width:
    baseline_phenotype: Platelet_distribution_width
    correction_method: Bonferroni
    n_training_genes: 40
  Red_blood_cell_erythrocyte_count:
    baseline_phenotype: Red_blood_cell_erythrocyte_count
    correction_method: Bonferroni
    n_training_genes: 40
  SHBG:
    baseline_phenotype: SHBG
    correction_method: Bonferroni
    n_training_genes: 40
  Standing_height:
    baseline_phenotype: Standing_height
    correction_method: Bonferroni
    n_training_genes: 40
  Total_bilirubin:
    baseline_phenotype: Total_bilirubin
    correction_method: Bonferroni
    n_training_genes: 40
  Total_protein:
    baseline_phenotype: Total_protein
    correction_method: Bonferroni
  Triglycerides:
    baseline_phenotype: Triglycerides
    correction_method: Bonferroni
    n_training_genes: 40
  Urate:
    baseline_phenotype: Urate
    correction_method: Bonferroni
    n_training_genes: 40
  Vitamin_D:
    baseline_phenotype: Vitamin_D
    correction_method: Bonferroni
  WHR_Body_mass_index_BMI_corrected:
    baseline_phenotype: WHR_Body_mass_index_BMI_corrected
    correction_method: Bonferroni
  Whole_body_fat_free_mass:
    baseline_phenotype: Whole_body_fat_free_mass
    correction_method: Bonferroni
pl_trainer:
  check_val_every_n_epoch: 1
  gpus: 1
  log_every_n_steps: 1
  max_epochs: 1000
  min_epochs: 50
  precision: 16
training:
  dataloader_config:
    batch_size: 1024
    cache_tensors: true
    chunksize: 100
    num_workers: 0
    temp_dir: $TMPDIR/deeprvat_train
  drop_n_bags: 0
  min_variant_count: 0
  n_bags: 1
  n_parallel_jobs: 6
  phenotypes:
  - Apolipoprotein_A
  - Apolipoprotein_B
  - Calcium
  - Cholesterol_statin_corrected
  - Red_blood_cell_erythrocyte_count
  - HDL_cholesterol
  - IGF_1
  - LDL_direct_statin_corrected
  - Lymphocyte_percentage
  - Mean_platelet_thrombocyte_volume
  - Mean_corpuscular_volume
  - Mean_reticulocyte_volume
  - Neutrophill_count
  - Platelet_count
  - Platelet_crit
  - Platelet_distribution_width
  - SHBG
  - Standing_height
  - Total_bilirubin
  - Triglycerides
  - Urate
  sample_with_replacement: false
  train_proportion: 0.8
training_data:
  dataloader_config:
    batch_size: 64
    num_workers: 8
  dataset_config:
    annotation_file: annotations.parquet
    annotations:
    - combined_UKB_NFE_AF
    - combined_UKB_NFE_AF_MB
    - CADD_PHRED
    - CADD_raw
    - sift_score
    - polyphen_score
    - Consequence_splice_acceptor_variant
    - Consequence_splice_donor_variant
    - Consequence_stop_gained
    - Consequence_frameshift_variant
    - Consequence_stop_lost
    - Consequence_start_lost
    - Consequence_inframe_insertion
    - Consequence_inframe_deletion
    - Consequence_missense_variant
    - Consequence_protein_altering_variant
    - Consequence_splice_region_variant
    - condel_score
    - DeepSEA_PC_1
    - DeepSEA_PC_2
    - DeepSEA_PC_3
    - DeepSEA_PC_4
    - DeepSEA_PC_5
    - DeepSEA_PC_6
    - PrimateAI_score
    - AbSplice_DNA
    - DeepRipe_plus_QKI_lip_hg2
    - DeepRipe_plus_QKI_clip_k5
    - DeepRipe_plus_KHDRBS1_clip_k5
    - DeepRipe_plus_ELAVL1_parclip
    - DeepRipe_plus_TARDBP_parclip
    - DeepRipe_plus_HNRNPD_parclip
    - DeepRipe_plus_MBNL1_parclip
    - DeepRipe_plus_QKI_parclip
    - SpliceAI_delta_score
    - alphamissense
    min_common_af:
      combined_UKB_NFE_AF: 0.01
    phenotype_file: phenotypes.parquet
    rare_embedding:
      config:
        annotations:
        - combined_UKB_NFE_AF_MB
        - CADD_raw
        - sift_score
        - polyphen_score
        - Consequence_splice_acceptor_variant
        - Consequence_splice_donor_variant
        - Consequence_stop_gained
        - Consequence_frameshift_variant
        - Consequence_stop_lost
        - Consequence_start_lost
        - Consequence_inframe_insertion
        - Consequence_inframe_deletion
        - Consequence_missense_variant
        - Consequence_protein_altering_variant
        - Consequence_splice_region_variant
        - condel_score
        - DeepSEA_PC_1
        - DeepSEA_PC_2
        - DeepSEA_PC_3
        - DeepSEA_PC_4
        - DeepSEA_PC_5
        - DeepSEA_PC_6
        - PrimateAI_score
        - AbSplice_DNA
        - DeepRipe_plus_QKI_lip_hg2
        - DeepRipe_plus_QKI_clip_k5
        - DeepRipe_plus_KHDRBS1_clip_k5
        - DeepRipe_plus_ELAVL1_parclip
        - DeepRipe_plus_TARDBP_parclip
        - DeepRipe_plus_HNRNPD_parclip
        - DeepRipe_plus_MBNL1_parclip
        - DeepRipe_plus_QKI_parclip
        - SpliceAI_delta_score
        - alphamissense
        low_memory: true
        thresholds:
          CADD_PHRED: CADD_PHRED > 5
          combined_UKB_NFE_AF: combined_UKB_NFE_AF < 1e-2
        verbose: true
      type: PaddedAnnotations
    sample_file: samples.pkl
    use_common_variants: false
    use_rare_variants: true
    verbose: true
    x_phenotypes:
    - age
    - age2
    - age_sex
    - genetic_sex
    - genetic_PC_1
    - genetic_PC_2
    - genetic_PC_3
    - genetic_PC_4
    - genetic_PC_5
    - genetic_PC_6
    - genetic_PC_7
    - genetic_PC_8
    - genetic_PC_9
    - genetic_PC_10
    - genetic_PC_11
    - genetic_PC_12
    - genetic_PC_13
    - genetic_PC_14
    - genetic_PC_15
    - genetic_PC_16
    - genetic_PC_17
    - genetic_PC_18
    - genetic_PC_19
    - genetic_PC_20
    y_transformation: quantile_transform
  gt_file: genotypes.h5
  variant_file: variants.parquet
