phenotypes:
    Apolipoprotein_A:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Apolipoprotein_A
    Apolipoprotein_B:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Apolipoprotein_B
    Calcium:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Calcium
    Cholesterol:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Cholesterol
    Red_blood_cell_erythrocyte_count:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Red_blood_cell_erythrocyte_count
    HDL_cholesterol:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: HDL_cholesterol
    IGF_1:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: IGF_1
    LDL_direct:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: LDL_direct
    Lymphocyte_percentage:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Lymphocyte_percentage
    Mean_platelet_thrombocyte_volume:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Mean_platelet_thrombocyte_volume
    Mean_corpuscular_volume:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Mean_corpuscular_volume
    Mean_reticulocyte_volume:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Mean_reticulocyte_volume
    Neutrophill_count:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Neutrophill_count
    Platelet_count:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Platelet_count
    Platelet_crit:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Platelet_crit
    Platelet_distribution_width:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Platelet_distribution_width
    SHBG:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: SHBG
    Standing_height:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Standing_height
    Total_bilirubin:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Total_bilirubin
    Triglycerides:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Triglycerides
    Urate:
        correction_method: FDR
        n_training_genes: 40
        baseline_phenotype: Urate


baseline_results:
    -
        base: #PATH_TO_BASELINE #put the path to the directory where deeprvat/pipelines/seed_gene_discovery.snakfile was run
        type: plof/burden
    -
        base: #PATH_TO_BASELINE 
        type: missense/burden
    -
        base:  #PATH_TO_BASELINE 
        type: plof/skat
    -
        base:#PATH_TO_BASELINE 
        type: missense/skat

alpha: 0.05

n_burden_chunks: 4
n_regression_chunks: 10

n_repeats: 6

training:
    min_variant_count: 1
    n_bags: 1
    drop_n_bags: 0
    train_proportion: 0.8
    sample_with_replacement: True
    dataloader_config:
        batch_size: 1024
        num_workers: 32

pl_trainer:
    gpus: 1
    precision: 16
    min_epochs: 50
    max_epochs: 1000
    log_every_n_steps: 1
    check_val_every_n_epoch: 1

early_stopping:
    mode: min
    patience: 3
    min_delta: 0.00001
    verbose: True

hyperparameter_optimization:
    direction: maximize
    n_trials: 1
    sampler:
        type: TPESampler
        config: {}

model:
    type: DeepSet
    model_collection: agg_models
    checkpoint: combined_agg.pt
    config:
        phi_layers: 2
            # hparam:
            #     type: int
            #     args:
            #         - 2
            #         - 4
        phi_hidden_dim: 20
            # hparam:
            #     type: int
            #     args:
            #         - 16
            #         - 64
            #     kwargs:
            #         step: 16
        rho_layers: 3
            # hparam:
            #     type: int
            #     args:
            #         - 2
            #         - 4
        rho_hidden_dim: 10
            # hparam:
            #     type: int
            #     args:
            #         - 8
            #         - 32
            #     kwargs:
            #         step: 8
        activation: LeakyReLU #was ReLU
            # hparam:
            #     type: categorical
            #     args:
            #         -
            #             - LeakyReLU
            #             - Tanh
        pool: max
            # hparam:
            #     type: categorical
            #     args:
            #         -
            #             - sum
            #             - max
        # dropout:
        #     hparam:
        #         type: float
        #         args:
        #             - 0.
        #             - 0.6
        #         kwargs:
        #             step: 0.1
        use_sigmoid: True
        metrics:
            # objective: PearsonCorrTorch
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}

training_data:
    gt_file: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/preprocessed/genotypes.h5
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_prefix: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/preprocessed/genotypes
        quantile_transform_y: True
        x_phenotypes:
            - age
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/annotations/current_annotations.parquet
        annotations:
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_raw
            - sift_score
            - polyphen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - condel_score
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI_score
            - AbSplice_DNA
            - DeepRipe_plus_QKI_lip_hg2
            - DeepRipe_plus_QKI_clip_k5
            - DeepRipe_plus_KHDRBS1_clip_k5
            - DeepRipe_plus_ELAVL1_parclip
            - DeepRipe_plus_TARDBP_parclip
            - DeepRipe_plus_HNRNPD_parclip
            - DeepRipe_plus_MBNL1_parclip
            - DeepRipe_plus_QKI_parclip
            - SpliceAI_delta_score
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - combined_UKB_NFE_AF_MB
                    - CADD_raw
                    - sift_score
                    - polyphen_score
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_inframe_insertion
                    - Consequence_inframe_deletion
                    - Consequence_missense_variant
                    - Consequence_protein_altering_variant
                    - Consequence_splice_region_variant
                    - condel_score
                    - DeepSEA_PC_1
                    - DeepSEA_PC_2
                    - DeepSEA_PC_3
                    - DeepSEA_PC_4
                    - DeepSEA_PC_5
                    - DeepSEA_PC_6
                    - PrimateAI_score
                    - AbSplice_DNA
                    - DeepRipe_plus_QKI_lip_hg2
                    - DeepRipe_plus_QKI_clip_k5
                    - DeepRipe_plus_KHDRBS1_clip_k5
                    - DeepRipe_plus_ELAVL1_parclip
                    - DeepRipe_plus_TARDBP_parclip
                    - DeepRipe_plus_HNRNPD_parclip
                    - DeepRipe_plus_MBNL1_parclip
                    - DeepRipe_plus_QKI_parclip
                    - SpliceAI_delta_score
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-2"
                    CADD_PHRED:  "CADD_PHRED > 5"
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 64
        num_workers: 8

data:
    gt_file: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/preprocessed/genotypes.h5
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_prefix: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/preprocessed/genotypes
        quantile_transform_y: True
        x_phenotypes:
            - age
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/annotations/current_annotations.parquet
        annotations:
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_raw
            - sift_score
            - polyphen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - condel_score
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI_score
            - AbSplice_DNA
            - DeepRipe_plus_QKI_lip_hg2
            - DeepRipe_plus_QKI_clip_k5
            - DeepRipe_plus_KHDRBS1_clip_k5
            - DeepRipe_plus_ELAVL1_parclip
            - DeepRipe_plus_TARDBP_parclip
            - DeepRipe_plus_HNRNPD_parclip
            - DeepRipe_plus_MBNL1_parclip
            - DeepRipe_plus_QKI_parclip
            - SpliceAI_delta_score
        gene_file: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/annotations/protein_coding_genes.parquet
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - combined_UKB_NFE_AF_MB
                    - CADD_raw
                    - sift_score
                    - polyphen_score
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_inframe_insertion
                    - Consequence_inframe_deletion
                    - Consequence_missense_variant
                    - Consequence_protein_altering_variant
                    - Consequence_splice_region_variant
                    - condel_score
                    - DeepSEA_PC_1
                    - DeepSEA_PC_2
                    - DeepSEA_PC_3
                    - DeepSEA_PC_4
                    - DeepSEA_PC_5
                    - DeepSEA_PC_6
                    - PrimateAI_score
                    - AbSplice_DNA
                    - DeepRipe_plus_QKI_lip_hg2
                    - DeepRipe_plus_QKI_clip_k5
                    - DeepRipe_plus_KHDRBS1_clip_k5
                    - DeepRipe_plus_ELAVL1_parclip
                    - DeepRipe_plus_TARDBP_parclip
                    - DeepRipe_plus_HNRNPD_parclip
                    - DeepRipe_plus_MBNL1_parclip
                    - DeepRipe_plus_QKI_parclip
                    - SpliceAI_delta_score
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-3"
                    CADD_PHRED:  "CADD_PHRED > 5"
                gene_file: /omics/odcf/analysis/OE0540_projects/ukbb/exomes/vcf/annotations/protein_coding_genes.parquet
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 16
        num_workers: 10
