phenotypes:
  - Apolipoprotein_A
  - Apolipoprotein_B
  - Calcium
  - Cholesterol_statin_corrected
  - HDL_cholesterol
  - IGF_1
  - LDL_direct_statin_corrected
  - SHBG
  - Total_bilirubin
  - Triglycerides
  - Urate
  - Standing_height
  - Lymphocyte_percentage
  - Mean_platelet_thrombocyte_volume
  - Mean_corpuscular_volume
  - Mean_reticulocyte_volume
  - Neutrophill_count
  - Platelet_count
  - Platelet_crit
  - Platelet_distribution_width
  - Red_blood_cell_erythrocyte_count
  - Body_mass_index_BMI
  - Glucose
  - Vitamin_D
  - Albumin
  - Total_protein
  - Cystatin_C
  - Gamma_glutamyltransferase
  - Alkaline_phosphatase
  - Creatinine
  - Whole_body_fat_free_mass
  - Forced_expiratory_volume_in_1_second_FEV1
  - Glycated_haemoglobin_HbA1c
  
######################### significant genes ############


gene_file: protein_coding_genes.parquet



######################### data preparation ############
prs_pheno_map: prs_pheno_map.csv
prs_file: PRS.parquet #should have sample ID as index and PGS{ID} as column names
phenotype_file: phenotypes.parquet
n_deeprvat_repeats: 6
deeprvat_run_dir: deeprvat_train_dir



regression:
    top_quantiles:
        - 0.001
        - 0.01
        - 0.1
    pheno_suffixes:
        - qt
    r_config:
        btypes:
            - deeprvat
            - plof
            - cadd
            - polyphen
            - sift
            - primateai
            - splicai
            - absplice
            - alphamissense
        gene_lists: 
            - deeprvat_discoveries
            - baseline_only

covariates:
    - age
    - age2
    - age_sex
    - genetic_sex
    - genetic_PC_1
    - genetic_PC_2
    - genetic_PC_3
    - genetic_PC_4
    - genetic_PC_5
    - genetic_PC_6
    - genetic_PC_7
    - genetic_PC_8
    - genetic_PC_9
    - genetic_PC_10
    - genetic_PC_11
    - genetic_PC_12
    - genetic_PC_13
    - genetic_PC_14
    - genetic_PC_15
    - genetic_PC_16
    - genetic_PC_17
    - genetic_PC_18
    - genetic_PC_19
    - genetic_PC_20
