---
title: "DeepRVAT - RVAT figures"
output:
  pdf_document: default
  html_notebook: default
---

Load libraries

```{r}
library(ggplot2)
library(arrow)
library(dplyr)
library(stringr)
library(tidyr)
library(ggpubr)
library(latex2exp)
```

Metadata

```{r}
phenotypes <- c(
  "Apolipoprotein_A",
  "Apolipoprotein_B",
  "Calcium",
  "Cholesterol",
  "HDL_cholesterol",
  "IGF_1",
  "LDL_direct",
  "Lymphocyte_percentage",
  "Mean_corpuscular_volume",
  "Mean_platelet_thrombocyte_volume",
  "Mean_reticulocyte_volume",
  "Neutrophill_count",
  "Platelet_count",
  "Platelet_crit",
  "Platelet_distribution_width",
  "Red_blood_cell_erythrocyte_count",
  "SHBG",
  "Standing_height",
  "Total_bilirubin",
  "Triglycerides",
  "Urate"
  )
```

Load DeepRVAT results

```{r}
results_dir <- "paper_experiment"

results_list <- list()
for (p in phenotypes) {
  results_list[[p]] <- read_parquet(file.path(results_dir, p, "deeprvat", "eval", "all_results.parquet"))
}

results <- bind_rows(results_list) %>%
  rename(Trait = phenotype) 
results

significant <- results %>%
  filter(significant) %>%
  distinct(Trait, Method, gene, .keep_all = TRUE)
significant

counts <- bind_rows(
  significant %>% mutate(is_single_trait = "True"),
  significant %>% mutate(Trait = "All traits", is_single_trait = "False")
) %>%
 mutate(
    Trait = case_match(
      Trait,
      "IGF 1" ~ "IGF-1",
      "Mean platelet thrombocyte volume" ~ "MPTV",
      "Red blood cell erythrocyte count" ~ "Erythrocyte count",
      .default = Trait
      )
  ) %>%
  mutate(
    Method = factor(Method),
    Trait = factor(Trait)
      ) %>%
  count(Trait, Method, is_single_trait, .drop = FALSE)
counts[is.na(counts$is_single_trait), "is_single_trait"] <- "True"
counts
```

Load Monti et al. results

```{r}
replication_monti_reimplemented <- readRDS("replication_monti_reimplemented.Rds") %>%
  filter(exp_name == "Monti-Rep Quantile-transformed") %>%
  mutate(Method = 'Monti et al.') 

counts_monti = replication_monti_reimplemented %>% 
  group_by(Trait, Method) %>% summarise(n = sum(Significant)) %>%
  mutate(is_single_trait = ifelse(Trait == 'All traits', 'False', 'True'))
counts_monti 
```

Load STAAR results

```{r}
replication_staar = readRDS('replication_staar.Rds') %>% mutate(Method = 'STAAR')
replication_staar$Trait <- str_replace(replication_staar$Trait, "All Traits",  'All traits')
replication_staar$Trait <- str_replace(replication_staar$Trait, "Mean platelet thrombocyte volume",  'MPTVS')

counts_staar = replication_staar %>% 
  group_by(Trait, Method) %>% summarise(n = sum(Significant)) %>%
  mutate(is_single_trait = ifelse(Trait == 'All traits', 'False', 'True')) 
 counts_staar
```

Combine results

```{r}
methods <- c('Burden pLOF', 'Burden missense', 'SKAT pLOF', 'SKAT missense', 'Burden/SKAT combined', "Monti et al.", "STAAR", 'DeepRVAT')

counts = rbind(counts, counts_monti, counts_staar) %>%
  filter(Method %in% methods) %>%
  mutate(Method = factor(Method, levels=methods)) %>%
  mutate(Trait = case_match(
    Trait,
    "MPTVS" ~ "MPTV",
    .default = Trait
  ))

counts %>% filter(Trait == "All traits")
counts %>% filter(Trait != "All traits")
levels(counts$Method)

counts %>% pivot_wider(names_from = Method, values_from = n)
```

ggplot2 theme

```{r}
colors <- c('#c6dbef', '#9ecae1', '#6baed6', '#3182bd', '#08519c', "aquamarine4", '#E6AB02', '#7A2961')


font_size <- 8
font_family <- "Helvetica"
plot_font <- element_text(size = font_size, family = font_family)

base_theme <- theme(
    text = element_text(size = font_size, family = font_family),
    axis.text = element_text(size = font_size, family = font_family),
    axis.title = element_text(size = font_size + 2, family = font_family),

    strip.text.x = element_blank(),
    strip.text.y = element_blank(),
    
    legend.title=element_blank(),
    
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA, linewidth = 0), #transparent plot bg
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent', color=NA), #transparent legend panel
)
```

Fig. 3a

```{r}
discovery_plot_alltraits <- ggplot(
    counts %>% filter(Trait == "All traits"),
    aes(
      x=Trait,
      y=n,
      fill=Method,
    )
) + 
geom_col(position='dodge', width=0.9, color='darkgray', linewidth=0.1) +
ylab("Significant gene-trait\nassociations") +
theme_classic() +
# facet_grid(. ~ is_single_trait, scales='free', space='free') +
base_theme + 
theme(
    axis.text.x=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
    axis.text.y=element_blank(),
    # axis.title.x=element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y=element_blank(),
    legend.key.size=unit(0.5, "line"),
    legend.text = element_text(size = font_size, family = font_family),
    legend.position = "bottom"
    #panel.spacing=unit(0.75, "cm"),
    #plot.margin = margin(1, 1, 1, 1, "cm"),
) +
scale_fill_manual(values = colors) +
  coord_flip() +
  guides(fill = guide_legend(nrow = 4))


ggsave("discoveries_alltraits.pdf", width = 7.25, height = 6, units = "cm", bg = "transparent")
discovery_plot_alltraits
```

Order traits

```{r}
traits <- sort(unique(counts$Trait))
```

Fig. 3c

```{r}
counts <- counts %>% 
  mutate(Trait = factor(Trait, levels = rev(traits))) %>%
  mutate(grid_column = (21 - as.integer(Trait)) %/% 7)

discovery_plot_singletraits <- ggplot(
    counts %>% filter(as.logical(is_single_trait)),
    aes(
      x=Trait,
      y=n,
      fill=Method,
    )
) + 
geom_col(position='dodge', width=0.9, color='darkgray', linewidth=0.1) +
ylab("Significant gene-trait associations") +
theme_classic() +
facet_wrap(vars(grid_column), scales='free') +
base_theme + 
theme(
    axis.text.x=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
    axis.text.y=element_text(angle=45, #vjust=1, hjust=1, 
                             size = font_size, family = font_family),
    axis.title.y=element_blank(),
    # axis.title.y=element_blank(),
    legend.key.size=unit(0.5, "line"),
    legend.position = "none",
    panel.spacing=unit(0.75, "cm"),
    # plot.margin = margin(1, 1, 1, 1, "cm"),
) +
scale_fill_manual(values = colors) +
  coord_flip()

ggsave("discoveries_singletraits.pdf", width = 15.5, height = 8, units = "cm", bg = "transparent")
discovery_plot_singletraits
```

Fig. 3b

```{r}
replication <- read_parquet(file.path(results_dir, "replication.parquet"))
# replication <- replication %>% rename("Rank" = "Gene rank", "Replicated" = "Replicated genes")
replication <- replication %>% 
  filter(pheno_grouping == "all_phenotypes")
replication

replication_monti_reimplemented_all_traits <- replication_monti_reimplemented %>%
  filter(Trait == "All traits") %>%
  rename(`Gene rank` = Rank, `Replicated genes` = Replicated)
replication_monti_reimplemented_all_traits

replication_staar_all_traits =  replication_staar %>% 
  filter(Trait == 'All traits') %>% 
  rename(`Gene rank` = Rank, `Replicated genes` = Replicated)
replication_staar_all_traits

replication <- bind_rows(replication, replication_monti_reimplemented_all_traits, replication_staar_all_traits)
replication

replication_full <- bind_rows(
  replication,
  replication_monti_reimplemented %>%
    rename(`Gene rank` = Rank, `Replicated genes` = Replicated),
  replication_staar %>% 
    rename(`Gene rank` = Rank, `Replicated genes` = Replicated)
) %>%
  mutate(Trait = case_match(
    Trait,
    "MPTVS" ~ "MPTV",
    .default = Trait
  ))
replication

replication$Significant <- recode(factor(replication$Significant, levels=c(TRUE, FALSE)), `TRUE` = "True", `FALSE` = "False")
replication_full$Significant <- recode(factor(replication_full$Significant, levels=c(TRUE, FALSE)), `TRUE` = "True", `FALSE` = "False")
replication

replication <- replication %>%
  mutate(Method = factor(Method, levels=methods)) %>%
  mutate(Trait = case_match(
    Trait,
    "MPTVS" ~ "MPTV",
    .default = Trait
  ))
replication

replication_plot <- ggplot(replication, aes(x=`Gene rank`, y=`Replicated genes`, color=Method)) +
geom_abline(intercept=0, slope=1, color='lightgray', linewidth=0.5) +
geom_step(linewidth=0.4, aes(linetype=Significant)) +
scale_color_manual(values = colors) +
theme_classic() +
base_theme +
theme(
    axis.text.x=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
    axis.text.y=element_text(angle=45, #vjust=1, hjust=1, 
                             size = font_size, family = font_family),
    legend.position = "none"
)

max_significant <- replication %>% 
  filter(as.logical(Significant)) %>% 
  group_by(Method) %>% 
  summarize(`Gene rank` = max(`Gene rank`), `Replicated genes` = max(`Replicated genes`))
max_significant
replication_plot <- replication_plot + geom_point(data=max_significant, aes(x=`Gene rank`, y=`Replicated genes`, color=Method))
replication_plot
```

Arrange Fig. 3 plots

```{r}
size_a <- list(width = 7.25, height = 6)
size_b <- list(width = 8, height = 6)
size_c <- list(width = 15.5, height = 8)

hjust <- 0.5
padding <- 0.25

fig3 <- ggarrange(
  ggarrange(
    NULL, discovery_plot_alltraits, replication_plot,
    labels = c("", "a", "b"),
    widths = c(padding, size_a$width, size_b$width),
    hjust = hjust,
    nrow = 1,
    ncol = 3),
  ggarrange(
    NULL, discovery_plot_singletraits,
    labels = c("", "c"),
    hjust = hjust,
    widths = c(padding, size_c$width)),
  nrow = 2,
  ncol = 1,
  heights = c(size_a$height, size_c$height)
  )
fig3

ggsave(
  filename = "fig3.png", 
  width = size_c$width, 
  height = size_a$height + size_c$height, 
  dpi = 600
  )
```

Supp. Fig. 3.3

```{r}
results_paper <- results %>%
  filter(Method == "DeepRVAT", `Discovery type` == "New DeepRVAT discovery")

results_dir <- "permutation_analysis"

results_list <- list()
for (p in phenotypes) {
  results_list[[p]] <- read_parquet(file.path(results_dir, p, "deeprvat", "eval", "all_results.parquet"))
}

results <- bind_rows(results_list) %>%
  rename(Trait = phenotype) %>%
  filter(Method == "DeepRVAT", `Discovery type` == "New DeepRVAT discovery") %>%
  mutate(Method = "DeepRVAT permuted")
results
```

```{r}
# colors <- c("#3182bd", '#7A2961')

#discovery_plot_alltraits <- ggplot(
#    counts,
#    aes(
#      x=Trait,
#      y=n,
#      fill=Method,
#    )
#) + 
#geom_col(position='dodge', width=0.9, color='darkgray', linewidth=0.1) +
#ylab("Significant gene-trait associations\n(new DeepRVAT discoveries)") +
#theme_classic() +
#base_theme + 
#theme(
#    axis.text.y=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
#    axis.text.x=element_blank(),
#    axis.ticks.x = element_blank(),
#    axis.title.x=element_blank(),
#    legend.key.size=unit(0.5, "line"),
#    legend.position = "bottom",
#    legend.title=element_blank()
#) +
#  scale_fill_manual(values = colors) +
#  # coord_flip() +
#  guides(fill = guide_legend(nrow = 2, byrow = TRUE))

#discovery_plot_alltraits
```

```{r}
prep_for_qqplot <- function(pval_df, group_name) {
  return(
    pval_df %>%
      arrange(pval) %>%
      mutate(
        neg_log10_pval_observed = -log10(pval),
        neg_log10_pval_expected = -log10((1:nrow(pval_df)) / nrow(pval_df))
      ) %>%
      mutate(clipped = neg_log10_pval_observed > 20) %>%
      mutate(neg_log10_pval_observed = pmin(neg_log10_pval_observed, 20))
  )
}

all_pvals <- read_parquet("all_pvals.parquet") %>% 
  filter(
    Trait %in% (results %>% distinct(Trait))$Trait,
    #trait_group == "Quantitative",
    Method %in% c("Burden/SKAT combined", "Monti et al.", "STAAR")
    )

pvals_for_qqplot <- bind_rows(
  results, 
  results_paper, 
  all_pvals
  ) %>%
  mutate(
    Method = case_match(
      Method,
      "DeepRVAT" ~ paste0("DeepRVAT - True phenotypes"),
      "DeepRVAT permuted" ~ paste0("DeepRVAT - Permuted phenotypes"),
      .default = Method
    )
  ) %>%
  group_by(Method) %>%
  group_modify(prep_for_qqplot)

compute_lambda <- function(pvals) {
  chisq <- qchisq(1 - pvals, 1)
  lambda <- median(chisq) / qchisq(0.5,1)
  return(format(round(lambda, 4), nsmall = 4))
}

lambda_baseline <- compute_lambda(filter(pvals_for_qqplot, Method == "Burden/SKAT combined")$pval)
lambda_monti <- compute_lambda(filter(pvals_for_qqplot, Method == "Monti et al.")$pval)
lambda_staar <- compute_lambda(filter(pvals_for_qqplot, Method == "STAAR")$pval)
lambda_true <- compute_lambda(filter(pvals_for_qqplot, grepl("True", Method))$pval)
lambda_perm <- compute_lambda(filter(pvals_for_qqplot, grepl("Permuted", Method))$pval)
```

```{r}
colors <- c('#08519c', "aquamarine4", '#E6AB02', '#7A2961', 'darkred')

pvals_for_qqplot <- pvals_for_qqplot %>%
  mutate(Method = factor(Method, levels = c("Burden/SKAT combined", "Monti et al.", "STAAR", "DeepRVAT - True phenotypes", "DeepRVAT - Permuted phenotypes")))

lambda_max <- 18
lambda_offset <- 2

qqplot <- ggplot(
  pvals_for_qqplot, 
#    mutate(
#      Method = case_match(
#        Method,
#        "paper_experiment" ~  "True",
#        "permutation_analysis" ~ "Permuted"
#      )
#    ), 
  aes(x = neg_log10_pval_expected, y = neg_log10_pval_observed, color = Method, shape = clipped)
  ) +
  geom_abline(intercept=0, slope=1, color='lightgray', linewidth=0.5) +
  geom_point(alpha = 0.5, size = 0.3) + 
  annotate(geom = "text", label = TeX(paste0(r"($\lambda = )", lambda_baseline, "$")), x = 1.5, y = lambda_max, color = colors[1]) +
  annotate(geom = "text", label = TeX(paste0(r"($\lambda = )", lambda_monti, "$")), x = 1.5, y = lambda_max - lambda_offset, color = colors[2]) +
  annotate(geom = "text", label = TeX(paste0(r"($\lambda = )", lambda_staar, "$")), x = 1.5, y = lambda_max - 2 * lambda_offset, color = colors[3]) +
  annotate(geom = "text", label = TeX(paste0(r"($\lambda = )", lambda_true, "$")), x = 1.5, y = lambda_max - 3 * lambda_offset, color = colors[4]) +
  annotate(geom = "text", label = TeX(paste0(r"($\lambda = )", lambda_perm, "$")), x = 1.5, y = lambda_max - 4 * lambda_offset, color = colors[5]) +
  scale_x_continuous(name=expression(Expected~~-log[10](italic(p)))) +
  scale_y_continuous(name=expression(Observed~~-log[10](italic(p)))) + 
  scale_color_manual(values = colors) +
  theme_classic() +
  base_theme +
  theme(
    legend.position = "bottom",
    legend.key.size = unit(12, "points")
  ) +
  guides(color = guide_legend(
    title="Trait values"),
    title.position = "top",
    override.aes = list(size=12),
    shape = "none")
#qqplot
```

```{r}
binary_counts_with_qc <- readRDS("binary_counts_with_qc.Rds")

scatter_theme = theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust =1 ),
        strip.background = element_rect(fill = "white", colour = "black", 
    linewidth = rel(2)),
    panel.grid = element_line(colour = "grey92"), 
            panel.grid.minor = element_line(linewidth = rel(0.5))
  ) 
p_cases_vs_discoveries = ggplot(binary_counts_with_qc %>% 
         filter(n_cases < 50000) %>%
         drop_na(), aes(x = n_cases , y = n)) +
  geom_point() +
  facet_wrap(vars(Method), ncol = 4) +
  scale_x_log10() +
  theme_classic() +
  scatter_theme +
  labs(y = 'Significant gene-trait associations', x = 'Number of cases')
p_cases_vs_discoveries
p_cases_vs_lambda = ggplot(binary_counts_with_qc %>% drop_na()  %>% filter(n_cases < 50000), aes(x = n_cases , y = lambda_gc)) +
  geom_point() +
  facet_wrap(vars(Method), ncol = 4) +
  theme_classic()+
  scatter_theme +
  scale_x_log10() +
  labs(y = 'Lambda GC', x = 'Number of cases')
p_cases_vs_lambda
```

```{r}
pad <- function(plot, width, height, left = 0, top = 0, right = 0, bottom = 0) {
  return(
    ggarrange(
      NULL,
      ggarrange(
        NULL, plot, NULL,
        widths = c(left, width, right),
        ncol = 3,
        nrow = 1
      ),
      NULL,
      heights = c(top, height, bottom),
      ncol = 1,
      nrow = 3
    )
  )
}

fig3.3 <- ggarrange(
  pad(qqplot, 7, 7, left = 3.75, right = 3.75),
  pad(p_cases_vs_discoveries, 15.5, 6, left = 0.5),
  pad(p_cases_vs_lambda, 15.5, 6, left = 0.5),
  labels = c("a", "b", "c"),
  heights = c(7, 6, 6),
  nrow = 3,
  ncol = 1
)
fig3.3

ggsave(
  filename = "fig3-3.png",
  width = 15.5,
  height = 18, 
  units = "cm",
  dpi = 600
  )
```

Supp. Fig. 3.4

```{r}
significant <- tibble()
for (dir in c("paper_experiment", "linear_model", "plof_missense_anno")) {
  for (p in phenotypes) {
    results_list[[p]] <- read_parquet(file.path(dir, p, "deeprvat", "eval", "all_results.parquet"))
  }
  
  results <- bind_rows(results_list) %>%
    rename(Trait = phenotype) %>%
    filter(Method == "DeepRVAT") %>%
    mutate(Method = dir)
  
  this_significant <- results %>%
    filter(significant) %>%
    distinct(Trait, Method, gene, .keep_all = TRUE)
  significant <- bind_rows(
    significant,
    this_significant
  )
}

significant

counts <- bind_rows(
  significant %>% mutate(is_single_trait = "True"),
  significant %>% mutate(Trait = "All traits", is_single_trait = "False")
) %>%
 mutate(
    Trait = case_match(
      Trait,
      "IGF 1" ~ "IGF-1",
      "Mean platelet thrombocyte volume" ~ "MPTV",
      "Red blood cell erythrocyte count" ~ "Erythrocyte count",
      .default = Trait
      )
  ) %>%
  mutate(
    Method = factor(Method),
    Trait = factor(Trait)
      ) %>%
  mutate(Method = case_match(
    Method,
    "paper_experiment" ~ "DeepRVAT",
    "linear_model" ~ "DeepRVAT-linear",
    "plof_missense_anno" ~ "DeepRVAT-missense/pLOF"
  )) %>%
  mutate(Method = factor(Method, levels = c("DeepRVAT-missense/pLOF", "DeepRVAT-linear", "DeepRVAT"))) %>%
  count(Trait, Method, is_single_trait, .drop = FALSE)
counts[is.na(counts$is_single_trait), "is_single_trait"] <- "True"
counts
```

```{r}
discovery_plot_alltraits <- ggplot(
    counts %>% filter(Trait == "All traits"),
    aes(
      x=Trait,
      y=n,
      fill=Method,
    )
) + 
geom_col(position='dodge', width=0.9, color='darkgray', linewidth=0.1) +
ylab("Significant gene-trait\nassociations") +
theme_classic() +
# facet_grid(. ~ is_single_trait, scales='free', space='free') +
base_theme + 
theme(
    axis.text.y=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
    axis.text.x=element_blank(),
    # axis.title.x=element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y=element_blank(),
    legend.key.size=unit(0.5, "line"),
    legend.text = element_text(size = font_size, family = font_family),
    legend.position = "bottom"
    #panel.spacing=unit(0.75, "cm"),
    #plot.margin = margin(1, 1, 1, 1, "cm"),
) +
  scale_fill_discrete(limits = rev) + 
  scale_fill_viridis_d(direction = -1) +
  guides(fill = guide_legend(reverse = TRUE, nrow = 1, byrow = TRUE))
discovery_plot_alltraits
```

```{r}
replication <- tibble()
for (dir in c("paper_experiment", "linear_model", "plof_missense_anno")) {
  this_replication <- read_parquet(file.path(dir, "replication.parquet"))
  this_replication <- this_replication %>% 
    filter(
      pheno_grouping == "all_phenotypes",
      Method == "DeepRVAT"
      ) %>%
    mutate(Method = dir)

  this_replication$Significant <- recode(factor(this_replication$Significant, levels=c(TRUE, FALSE)), `TRUE` = "True", `FALSE` = "False")

  replication <- bind_rows(
    replication,
    this_replication
  )
}
replication <- replication %>%
  mutate(Method = case_match(
    Method,
    "paper_experiment" ~ "DeepRVAT",
    "linear_model" ~ "DeepRVAT-linear",
    "plof_missense_anno" ~ "DeepRVAT-missense/pLOF"
  ))

replication_plot <- ggplot(replication, aes(x=`Gene rank`, y=`Replicated genes`, color=Method)) +
geom_abline(intercept=0, slope=1, color='lightgray', linewidth=0.5) +
geom_step(linewidth=0.4, aes(linetype=Significant)) +
scale_color_viridis_d() +
theme_classic() +
base_theme +
  theme(legend.position = "none")

max_significant <- replication %>% 
  filter(as.logical(Significant)) %>% 
  group_by(Method) %>% 
  summarize(`Gene rank` = max(`Gene rank`), `Replicated genes` = max(`Replicated genes`))
max_significant
replication_plot <- replication_plot + geom_point(data=max_significant, aes(x=`Gene rank`, y=`Replicated genes`, color=Method))

replication_plot
```

```{r}
size_b <- list(width = 10.1, height = 10.1)
size_null <- list(width = 0.4, height = 0.3)
size_a <- list(width = 5, height = size_b$height)

fig3.4 <- ggarrange(
  NULL, 
  ggarrange(
    discovery_plot_alltraits + theme(legend.position = "none"),
    NULL,
    widths = c(size_a$width, size_a$width),
    heights = c(size_a$height - size_null$height, size_null$height),
    nrow = 2,
    ncol = 1
  ),
  replication_plot,
  labels = c("a", "", "b"),
  widths = c(size_null$width, size_a$width, size_b$width),
  nrow = 1,
  ncol = 3,
  common.legend = TRUE,
  legend.grob = get_legend(discovery_plot_alltraits)
)
fig3.4

ggsave(
  filename = "fig3-4.png",
  width = size_null$width + size_a$width + size_b$width,
  height = size_a$height, 
  units = "cm",
  dpi = 600
  )
```


Supp. Fig. 3.7

```{r}
results_dir <- "repeat_analysis"

results_list <- list()
for (p in phenotypes) {
  results_list[[p]] <- read_parquet(file.path(results_dir, p, "deeprvat", "eval", "all_results.parquet")) %>%
    filter(Method == "DeepRVAT") %>%
    mutate(Method = paste("DeepRVAT", repeats, "repeats")) %>%
    rename(Repeats = repeats)
}

results <- bind_rows(results_list) %>%
  rename(Trait = phenotype)
```

```{r}
significant <- results %>%
  filter(significant) %>%
  distinct(Trait, Method, Repeats, gene, .keep_all = TRUE)
significant

counts <- bind_rows(
  significant %>% mutate(is_single_trait = "True"),
  significant %>% mutate(Trait = "All traits", is_single_trait = "False")
) %>%
 mutate(
    Trait = case_match(
      Trait,
      "IGF 1" ~ "IGF-1",
      "Mean platelet thrombocyte volume" ~ "MPTV",
      "Red blood cell erythrocyte count" ~ "Erythrocyte count",
      .default = Trait
      )
  ) %>%
  mutate(
    Method = factor(Method),
    Trait = factor(Trait)
      ) %>%
  count(Trait, Method, Repeats, is_single_trait, .drop = FALSE)
counts[is.na(counts$is_single_trait), "is_single_trait"] <- "True"
counts
```

```{r}
discovery_plot_alltraits <- ggplot(
    counts %>% filter(Trait == "All traits"),
    aes(
      x=Repeats,
      y=n #,
      # fill=Method,
    )
) + 
geom_line() +
ylab("Significant gene-trait associations") +
theme_classic() +
# facet_grid(. ~ is_single_trait, scales='free', space='free') +
base_theme + 
theme(
    #axis.text.x=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
    #axis.text.y=element_blank(),
    # axis.title.x=element_blank(),
    legend.key.size=unit(0.5, "line"),
    legend.position = "bottom"
    #panel.spacing=unit(0.75, "cm"),
    #plot.margin = margin(1, 1, 1, 1, "cm"),
) +
# scale_fill_manual(values = colors) +
  scale_x_continuous(breaks = 1:10) +
  scale_y_continuous(limits = c(0, NA)) +
  guides(fill = guide_legend(nrow = 3))

# ggsave("discoveries_alltraits.pdf", width = 7.25, height = 6, units = "cm", bg = "transparent")
discovery_plot_alltraits
```

```{r}
replication <- read_parquet(file.path(results_dir, "replication.parquet"))
# replication <- replication %>% rename("Rank" = "Gene rank", "Replicated" = "Replicated genes")
replication <- replication %>%
  filter(Method == "DeepRVAT", pheno_grouping == "all_phenotypes") %>%
  mutate(
    Method = factor(paste("DeepRVAT", repeats, "repeats"), levels = paste("DeepRVAT", 1:10, "repeats")),
    Trait = case_match(
      Trait,
      "MPTVS" ~ "MPTV",
      .default = Trait
      )
    )
replication

replication$Significant <- recode(factor(replication$Significant, levels=c(TRUE, FALSE)), `TRUE` = "True", `FALSE` = "False")
#replication_full$Significant <- recode(factor(replication_full$Significant, levels=c(TRUE, FALSE)), `TRUE` = "True", `FALSE` = "False")
replication

#replication <- replication %>%
#  mutate(Method = factor(Method, levels=methods)) %>%
#  mutate(Trait = case_match(
#    Trait,
#    "MPTVS" ~ "MPTV",
#    .default = Trait
#  ))
#replication

replication_plot <- ggplot(replication, aes(x=`Gene rank`, y=`Replicated genes`, color=Method)) +
geom_abline(intercept=0, slope=1, color='lightgray', linewidth=0.5) +
geom_step(linewidth=0.4, aes(linetype=Significant)) +
scale_color_viridis_d() +
theme_classic() +
base_theme +
theme(
    axis.text.x=element_text(angle=45, vjust=1, hjust=1, size = font_size, family = font_family),
    axis.text.y=element_text(angle=45, #vjust=1, hjust=1, 
                             size = font_size, family = font_family),
    legend.position = "bottom"
) + 
  guides(linetype = FALSE)

max_significant <- replication %>% 
  filter(as.logical(Significant)) %>% 
  group_by(Method) %>% 
  summarize(`Gene rank` = max(`Gene rank`), `Replicated genes` = max(`Replicated genes`))
max_significant
replication_plot <- replication_plot + geom_point(data=max_significant, aes(x=`Gene rank`, y=`Replicated genes`, color=Method))
replication_plot
```


```{r}
size_b <- list(width = 10.1, height = 10.1)
size_null <- list(width = 0.4, height = 0.4)
size_a <- list(width = 5, height = size_b$height)

fig3.7 <- ggarrange(
  NULL, 
  ggarrange(
    discovery_plot_alltraits + theme(legend.position = "none"),
    NULL,
    widths = c(size_a$width, size_a$width),
    heights = c(size_a$height - size_null$height, size_null$height),
    nrow = 2,
    ncol = 1
  ),
  replication_plot,
  labels = c("a", "", "b"),
  widths = c(size_null$width, size_a$width, size_b$width),
  nrow = 1,
  ncol = 3,
  common.legend = TRUE,
  legend.grob = get_legend(replication_plot)
)
fig3.7

ggsave(
  filename = "fig3-7.png",
  width = size_null$width + size_a$width + size_b$width,
  height = size_a$height, 
  units = "cm",
  dpi = 600
  )
```