phenotypes:
  - Jurgens_Hypertension 
  - Jurgens_Hypercholesterolemia 
  - Jurgens_Osteoarthritis 
  - Jurgens_Asthma
  - Jurgens_Gastroesophageal_reflux_disease
  - Jurgens_Diverticular_disease
  - Jurgens_Depression 
  - Jurgens_Cataract 
  - Jurgens_Allergic_rhinitis 
  - Jurgens_Hypothyroidism 
  - Jurgens_Diabetes_Type_2 
  - Jurgens_Skin_cancer
  - Jurgens_Back_pain
  - Jurgens_Cholelithiasis 
  - Jurgens_Pneumonia
  - Jurgens_Atrial_fibrillation 
  - Jurgens_Coronary_Artery_Disease
  - Jurgens_Migraine
  - Jurgens_Dermatitis 
  - Jurgens_Irritable_bowel_syndrome 
  - Jurgens_Chronic_obstructive_pulmonary_disease 
  - Jurgens_Venous_thromboembolism 
  - Jurgens_Breast_cancer 
  - Jurgens_Osteoporosis 
  - Jurgens_Myocardial_infarction 
  - Jurgens_Stroke

baseline_results:
    -
        base: baseline_results
        type: plof/burden
    -
        base: baseline_results
        type: missense/burden
    -
        base: baseline_results
        type: plof/skat
    -
        base: baseline_results #PATH_TO_BASELINE 
        type: missense/skat

alpha: 0.05

n_burden_chunks: 4
n_regression_chunks: 2

n_repeats: 6

do_scoretest: True


model:
    type: DeepSet
    model_collection: agg_models
    checkpoint: combined_agg.pt
    config:
        phi_layers: 2
        phi_hidden_dim: 20
        rho_layers: 3
        rho_hidden_dim: 10
        activation: LeakyReLU
        pool: max
        use_sigmoid: True
        metrics:
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}


data:
    gt_file: genotypes.h5
    variant_file: variants.parquet
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_file: phenotypes.parquet
        x_phenotypes:
            - age
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: annotations.parquet
        annotations:
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_raw
            - sift_score
            - polyphen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - condel_score
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI_score
            - AbSplice_DNA
            - DeepRipe_plus_QKI_lip_hg2
            - DeepRipe_plus_QKI_clip_k5
            - DeepRipe_plus_KHDRBS1_clip_k5
            - DeepRipe_plus_ELAVL1_parclip
            - DeepRipe_plus_TARDBP_parclip
            - DeepRipe_plus_HNRNPD_parclip
            - DeepRipe_plus_MBNL1_parclip
            - DeepRipe_plus_QKI_parclip
            - SpliceAI_delta_score
        gene_file: protein_coding_genes.parquet
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - combined_UKB_NFE_AF_MB
                    - CADD_raw
                    - sift_score
                    - polyphen_score
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_inframe_insertion
                    - Consequence_inframe_deletion
                    - Consequence_missense_variant
                    - Consequence_protein_altering_variant
                    - Consequence_splice_region_variant
                    - condel_score
                    - DeepSEA_PC_1
                    - DeepSEA_PC_2
                    - DeepSEA_PC_3
                    - DeepSEA_PC_4
                    - DeepSEA_PC_5
                    - DeepSEA_PC_6
                    - PrimateAI_score
                    - AbSplice_DNA
                    - DeepRipe_plus_QKI_lip_hg2
                    - DeepRipe_plus_QKI_clip_k5
                    - DeepRipe_plus_KHDRBS1_clip_k5
                    - DeepRipe_plus_ELAVL1_parclip
                    - DeepRipe_plus_TARDBP_parclip
                    - DeepRipe_plus_HNRNPD_parclip
                    - DeepRipe_plus_MBNL1_parclip
                    - DeepRipe_plus_QKI_parclip
                    - SpliceAI_delta_score
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-3"
                    CADD_PHRED:  "CADD_PHRED > 5"
                gene_file: protein_coding_genes.parquet
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 16
        num_workers: 10
