
phenotypes:
  - Jurgens_Hypertension 
  - Jurgens_Hypercholesterolemia 
  - Jurgens_Osteoarthritis 
  - Jurgens_Asthma
  - Jurgens_Gastroesophageal_reflux_disease
  - Jurgens_Diverticular_disease
  - Jurgens_Depression 
  - Jurgens_Cataract 
  - Jurgens_Allergic_rhinitis 
  - Jurgens_Hypothyroidism 
  - Jurgens_Diabetes_Type_2 
  - Jurgens_Skin_cancer
  - Jurgens_Back_pain
  - Jurgens_Cholelithiasis 
  - Jurgens_Pneumonia
  - Jurgens_Atrial_fibrillation 
  - Jurgens_Coronary_Artery_Disease
  - Jurgens_Migraine
  - Jurgens_Dermatitis 
  - Jurgens_Irritable_bowel_syndrome 
  - Jurgens_Chronic_obstructive_pulmonary_disease 
  - Jurgens_Venous_thromboembolism 
  - Jurgens_Breast_cancer 
  - Jurgens_Osteoporosis 
  - Jurgens_Myocardial_infarction 
  - Jurgens_Stroke

  
variant_types:
    - missense
    - plof

n_chunks: 15
test_types:
   - skat
   - burden

rare_maf: 0.001


#debug: True
alpha: 0.05


test_config:
    center_genotype: True
    neglect_homozygous: False
    collapse_method: sum #collapsing method for burde
    var_weight_function: beta_maf 
    min_mac: 10
variant_file: variants.parquet

data:
    gt_file: genotypes.h5
    dataset_config:
        variant_file: variants.parquet
        phenotype_file: phenotypes.parquet
        standardize_xpheno: False
        min_common_af:
            MAF: 0.001 #is updated automatically when updating the config with update_config
        x_phenotypes:
            - age
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: annotations.parquet
        annotations:
            - MAF
            - is_plof
            - Consequence_missense_variant
        gene_file: protein_coding_genes.parquet
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: SparseGenotype 
            config:
                annotations:
                    - MAF
                    - is_plof
                    - Consequence_missense_variant
                gene_file: protein_coding_genes.parquet
                verbose: True
        verbose: True
    dataloader_config:
        num_workers: 10
        #batch_size: 20


