phenotypes:
    Apolipoprotein_A:
        correction_method: Bonferroni 
    Apolipoprotein_B:
        correction_method: Bonferroni 
    Calcium:
        correction_method: Bonferroni 
    Cholesterol_statin_corrected:
        correction_method: Bonferroni 
    HDL_cholesterol:
        correction_method: Bonferroni 
    IGF_1:
        correction_method: Bonferroni 
    LDL_direct_statin_corrected:
        correction_method: Bonferroni 
    Lymphocyte_percentage:
        correction_method: Bonferroni 
    Mean_corpuscular_volume:
        correction_method: Bonferroni 
    Mean_platelet_thrombocyte_volume:
        correction_method: Bonferroni 
    Mean_reticulocyte_volume:
        correction_method: Bonferroni 
    Neutrophill_count:
        correction_method: Bonferroni 
    Platelet_count:
        correction_method: Bonferroni 
    Platelet_crit:
        correction_method: Bonferroni 
    Platelet_distribution_width:
        correction_method: Bonferroni 
    Red_blood_cell_erythrocyte_count:
        correction_method: Bonferroni 
    SHBG:
        correction_method: Bonferroni 
    Standing_height:
        correction_method: Bonferroni 
    Total_bilirubin:
        correction_method: Bonferroni 
    Triglycerides:
        correction_method: Bonferroni 
    Urate:
        correction_method: Bonferroni 

baseline_results:
    -
        base: baseline_results
        type: plof/burden
    -
        base: baseline_results
        type: missense/burden
    -
        base: baseline_results
        type: plof/skat
    -
        base: baseline_results
        type: missense/skat

cv_path: sample_files
n_folds: 5
alpha: 0.05

n_burden_chunks: 5
n_regression_chunks: 2

n_repeats: 6

do_scoretest: True

training:
    min_variant_count: 0
    n_bags: 1
    drop_n_bags: 0
    train_proportion: 0.8
    sample_with_replacement: False
    n_parallel_jobs: 6
    dataloader_config:
        batch_size: 1024
        num_workers: 0
        temp_dir: $TMPDIR/deeprvat_train
        cache_tensors: True
        chunksize: 100
    phenotypes:
        - Apolipoprotein_A
        - Apolipoprotein_B
        - Calcium
        - Cholesterol_statin_corrected
        - Red_blood_cell_erythrocyte_count
        - HDL_cholesterol
        - IGF_1
        - LDL_direct_statin_corrected
        - Lymphocyte_percentage
        - Mean_platelet_thrombocyte_volume
        - Mean_corpuscular_volume
        - Mean_reticulocyte_volume
        - Neutrophill_count
        - Platelet_count
        - Platelet_crit
        - Platelet_distribution_width
        - SHBG
        - Standing_height
        - Total_bilirubin
        - Triglycerides
        - Urate


pl_trainer:
    gpus: 1
    precision: 16
    min_epochs: 50
    max_epochs: 1000
    log_every_n_steps: 1
    check_val_every_n_epoch: 1

early_stopping:
    mode: min
    patience: 3
    min_delta: 0.00001
    verbose: True

hyperparameter_optimization:
    direction: maximize
    n_trials: 1
    sampler:
        type: TPESampler
        config: {}

model:
    type: DeepSet
    model_collection: agg_models
    checkpoint: combined_agg.pt
    config:
        phi_layers: 2
        phi_hidden_dim: 20
        rho_layers: 3
        rho_hidden_dim: 10
        activation: LeakyReLU
        pool: max
        use_sigmoid: True
        metrics:
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}

training_data:
    gt_file: genotypes.h5
    variant_file: variants.parquet
    dataset_config:
        min_common_af:
            MAF: 0.01
        phenotype_file: phenotypes.parquet
        y_transformation: quantile_transform
        x_phenotypes:
            - age
            - age2
            - age_sex
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: annotations.parquet
        annotations:
            - MAF
            - MAF_MB
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_missense_variant
            - CADD_PHRED
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - MAF_MB
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_missense_variant
                thresholds:
                    MAF: "MAF < 1e-2"
                    CADD_PHRED:  "CADD_PHRED > 5"
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 64
        num_workers: 8

data:
    gt_file: genotypes.h5
    variant_file: variants.parquet
    dataset_config:
        min_common_af:
            MAF: 0.01
        phenotype_file: phenotypes.parquet
        y_transformation: quantile_transform
        x_phenotypes:
            - age
            - age2
            - age_sex
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: annotations.parquet
        annotations:
            - MAF_MB
            - MAF
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_missense_variant
            - CADD_PHRED
        gene_file: protein_coding_genes.parquet
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - MAF_MB
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_missense_variant
                thresholds:
                    MAF: "MAF < 1e-3"
                    CADD_PHRED:  "CADD_PHRED > 5"
                gene_file: protein_coding_genes.parquet
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 16
        num_workers: 10
